"""E2E tests for the AgentsTV dashboard view."""

import pytest
from playwright.sync_api import expect


def test_dashboard_loads(page):
    """Page title or heading contains AgentsTV."""
    title = page.title()
    assert "AgentsTV" in title


def test_dashboard_has_search(page):
    """Search input is visible on the dashboard."""
    search = page.locator("#session-search")
    expect(search).to_be_visible()
    expect(search).to_have_attribute("placeholder", "Search projects, branches...")


def test_dashboard_has_sort(page):
    """Sort dropdown is visible on the dashboard."""
    sort_select = page.locator("#session-sort")
    expect(sort_select).to_be_visible()
    # Verify at least some options exist
    options = sort_select.locator("option")
    assert options.count() >= 2


def test_session_cards_render(page):
    """Session grid exists and renders without crashing (may be empty)."""
    grid = page.locator("#session-grid")
    expect(grid).to_be_visible()
    # Cards may or may not exist depending on local sessions — just verify no crash
    page.wait_for_timeout(2000)
    cards = page.locator(".session-card")
    count = cards.count()
    assert count >= 0  # Sanity: no exception thrown


def test_master_card_visible(page):
    """Dashboard should contain a link or card for master control room."""
    # The master control room link is generated by dashboard.js as a session card
    # with a special class or the #/master link. Wait a bit for WS data.
    page.wait_for_timeout(2000)
    # Check if any link points to #/master
    master_link = page.locator("a[href='#/master'], [data-href='#/master'], .master-card")
    # Master card may not render if no sessions exist, so just verify no crash
    if master_link.count() > 0:
        expect(master_link.first).to_be_visible()


def test_no_sessions_message(page):
    """If no session cards, the empty-state message should be visible."""
    page.wait_for_timeout(2000)
    cards = page.locator(".session-card")
    if cards.count() == 0:
        no_sessions = page.locator("#no-sessions")
        # Either hidden or shown — just check it exists in DOM
        assert no_sessions.count() == 1


def test_search_filters(page):
    """Typing a search term filters session cards or at least does not crash."""
    page.wait_for_timeout(1000)
    search = page.locator("#session-search")
    initial_count = page.locator(".session-card").count()

    search.fill("zzz_nonexistent_project_zzz")
    page.wait_for_timeout(500)
    filtered_count = page.locator(".session-card").count()

    # Either filtering reduced count or there were 0 cards to begin with
    assert filtered_count <= initial_count

    # Clear search to restore state
    search.fill("")
    page.wait_for_timeout(500)
    restored_count = page.locator(".session-card").count()
    assert restored_count >= filtered_count


def test_logo_visible(page):
    """The AgentsTV logo text should be visible in the top bar."""
    logo = page.locator(".logo")
    expect(logo.first).to_be_visible()
    expect(logo.first).to_contain_text("AgentsTV")
